import './globals.css';

import { Footer } from '@/coponents/complex/Footer';
import { ReactNode } from 'react';

import styles from './layout.module.scss';

import type { Metadata } from 'next'
import Header from '@/coponents/complex/Header/Header';
import LayoutSigIn from './layoutSigIn';

export const metaDataAuth: Metadata = {
  title: 'Войди пожалуйста :)',
  description: 'Нужно войти чтобы использовать фунционал моего сайта ',

}

export const metadata: Metadata = true ? metaDataAuth : {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// console.log(CssBaseline.flush())
export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.wrapper} >
        {
          false ?
            <>
              <Header />
              <div className={styles.content}>
                {children}
              </div>
              <Footer />
            </>
            : 
            <LayoutSigIn>
                {children}
            </LayoutSigIn>
        }
      </body>
    </html>
  )
}
